### ISSUE TITLE
Autumnal Cleanup 2015 Reporting

### ISSUE THREAD

**Issue by StreakyCobra** [StreakyCobra/test_wiki#3]
This issue is used to report contributors' work on the [Autumnal Cleanup 2015](https://github.com/syl20bnr/spacemacs/wiki/Autumnal-Cleanup-2015).

**Please don't discuss or ask anything here**. If you want to participate, read the page linked above and go on [Gitter](https://gitter.im/syl20bnr/spacemacs) to discuss it :smile: This thread is only used to report work by adding comments of the form:

```
- [ ] #1 Valid
- [ ] #2 Wontfix
- [ ] #3 NRA
- [ ] #4 Can't reproduce
...
```

Also don't fill checkboxes yourself, as they will be used by maintainers to mark their progression.

**Comment by StreakyCobra** [comment]
@fabien Here are some issues for you:

- #3224 **sr-speedbar layer** **
- #1647 **Enlarging font overlaps the line numbers** *bug :-(*
- #2315 **Spacemacs crashes on OS X when the system starts to sleep** *OS X*
- #1265 **desktop-save-mode blocks startup of spacemacs** *bug :-(*
- #1687 **C-j not work in ido-find-file** **

Please confirm you take them, so I can block those ones for the next 2 weeks :-)

**Comment by fabien** [comment]
@StreakyCobra wrong @fabien mention

**Comment by StreakyCobra** [comment]
Oups, sorry, I was playing a bit, It's also my first name ;-)
